### PR TITLE
do not emit warnings for either httpclient versions 2.6 or 2.7

### PR DESCRIPTION
**Pull request by mwrock**

### CODE REVIEW

**Comment by mwrock** [comment]
cc @chef/client-windows

**Comment by danielsdeleo** [comment]
:+1: Just wondering, though, do we have any long term ideas about how to not need to do this?

**Comment by mwrock** [comment]
YES. waiting for https://github.com/nahi/httpclient/pull/290 to merge and then I'll add the winrm patches to winrm. Will be awesome to get this included in their rightful homes.

**Comment by adamedx** [comment]
:+1: . @danielsdeleo, the long term plan is for the fix to be merged upstream, and then to deprecate the winrm-s gem and only use the `winrm` gem.

**Pull request merged**
